artifact_uri: file:///D:/Personal/CampusX/yt-comment-sentiment-analysis/gshub.com/ranitsarkar/test_exp_tracking_yt_analysis.mlflow/595082985908774983/0be5cfceb4e346a2a07da96aaae1d736/artifacts
end_time: 1732214891386
entry_point_name: ''
experiment_id: '595082985908774983'
lifecycle_stage: active
run_id: 0be5cfceb4e346a2a07da96aaae1d736
run_name: secretive-bee-597
run_uuid: 0be5cfceb4e346a2a07da96aaae1d736
source_name: ''
source_type: 4
source_version: ''
start_time: 1732214884170
status: 3
tags: []
user_id: ranitsarkar
