channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.0.1
- pip:
  - mlflow==2.18.0
  - cffi==1.17.1
  - cloudpickle==3.1.0
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==6.1.0
  - pyarrow==18.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
