artifact_location: file:///D:/Personal/CampusX/yt-comment-sentiment-analysis/gshub.com/ranitsarkar/test_exp_tracking_yt_analysis.mlflow/595082985908774983
creation_time: 1732214883871
experiment_id: '595082985908774983'
last_update_time: 1732214883871
lifecycle_stage: active
name: dvc-pipeline-runs
